### ISSUE TITLE
Failed to compile on Apache/2.2.3 (Linux/SUSE)

### ISSUE THREAD

**Issue by xhat007** [VladRico/apache2_BackdoorMod#1]
Hi,
Im strugglling to compile the apache backdoor on OpenSUSE 10.2 Runing Apache 2.2.3

**root-2:/var/www/html/ # apxs2 -i -a -c mod_backdoor.c sblist.c sblist_delete.c server.c -Wl,-lutil**

```
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -prefer-pic -O2 -fmessage-length=0 -Wall -D_FORTIFY_SOURCE=2 -g -fPIC -Wall -fno-strict-aliasing -DLDAP_DEPRECATED  -DLINUX=2 -D_REENTRANT -D_GNU_SOURCE -DAP_DEBUG -pthread -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1   -c -o mod_backdoor.lo mod_backdoor.c && touch mod_backdoor.slo
In file included from mod_backdoor.c:43:
mod_backdoor.h:17: error: redefinition of typedef 'apr_socket_t'
/usr/include/apr-1/apr_network_io.h:190: error: previous declaration of 'apr_socket_t' was here
In file included from mod_backdoor.c:43:
mod_backdoor.h:21:41: warning: no newline at end of file
mod_backdoor.c:47:1: warning: "_GNU_SOURCE" redefined
<command line>:1:1: warning: this is the location of the previous definition
mod_backdoor.c:48:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/sys/types.h:27,
                 from mod_backdoor.c:11:
/usr/include/features.h:154:1: warning: this is the location of the previous definition
In file included from mod_backdoor.c:51:
server.h:11: warning: ignoring #pragma RcB2 DEP
In file included from mod_backdoor.c:52:
sblist.h:90: warning: ignoring #pragma RcB2 DEP
mod_backdoor.c: In function 'send_auth_response':
mod_backdoor.c:268: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'send_error':
mod_backdoor.c:275: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'clientthread':
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of 'strlen' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of 'strlen' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of '__builtin_strcmp' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of 'strlen' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of '__builtin_strcmp' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of '__builtin_strcmp' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of '__builtin_strcmp' differ in signedness
mod_backdoor.c:341: warning: pointer targets in passing argument 1 of 'strncmp' differ in signedness
mod_backdoor.c: In function 'shell':
mod_backdoor.c:470: warning: unused variable 'buf'
mod_backdoor.c:469: warning: unused variable 'sr'
mod_backdoor.c:469: warning: unused variable 'n'
mod_backdoor.c:475: warning: ignoring return value of 'pipe', declared with attribute warn_unused_result
mod_backdoor.c:476: warning: ignoring return value of 'pipe', declared with attribute warn_unused_result
mod_backdoor.c: In function 'shellPTY':
mod_backdoor.c:626: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:636: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'bindPort':
mod_backdoor.c:656: error: 'SO_REUSEPORT' undeclared (first use in this function)
mod_backdoor.c:656: error: (Each undeclared identifier is reported only once
mod_backdoor.c:656: error: for each function it appears in.)
mod_backdoor.c:663: warning: unused variable 'serverlen'
mod_backdoor.c:652: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:669: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:674: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'bicomIPC':
mod_backdoor.c:714: warning: 'return' with no value, in function returning non-void
mod_backdoor.c:700: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:709: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'backdoor_post_read_request':
mod_backdoor.c:830: warning: unused variable 'i'
mod_backdoor.c:830: warning: unused variable 'sd'
mod_backdoor.c:829: warning: unused variable 'buf'
mod_backdoor.c:721: warning: unused variable 'tv'
mod_backdoor.c:719: warning: unused variable 'readset'
mod_backdoor.c:718: warning: unused variable 'sr'
mod_backdoor.c:718: warning: unused variable 'n'
mod_backdoor.c:757: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:764: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:768: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:770: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:782: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:790: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:800: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:816: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:823: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:833: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:840: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:844: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:851: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:866: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:881: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:888: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:895: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:900: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c:904: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'rmCgroup':
mod_backdoor.c:930: warning: passing argument 4 of 'mount' makes integer from pointer without a cast
mod_backdoor.c:923: warning: unused variable 'thisPID'
mod_backdoor.c:939: warning: ignoring return value of 'write', declared with attribute warn_unused_result
mod_backdoor.c: In function 'backdoor_post_config':
mod_backdoor.c:1034: warning: unused variable 'readfds'
mod_backdoor.c:1033: warning: unused variable 'buf'
mod_backdoor.c:1031: warning: unused variable 'sr'
apxs:Error: Command failed with rc=65536
```

**Any help will be appreciated.**

**Comment by VladRico** [comment]
Have you already tried to patch these errors ?
`mod_backdoor.h:17: error: redefinition of typedef 'apr_socket_t'`
--> remove `apr_socket_t` definiton

`error: 'SO_REUSEPORT' undeclared (first use in this function)`
--> it's added in linux kernel 3.9: [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c617f398edd4db2b8567a28e899a88f8f574798d)
So you've to find a way to bypass that or maybe you could remove it
